import { Product, Category, Supplier } from '@/types/erp.types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Excitantes', description: 'Géis, saca-rolhas e estimulantes sensoriais', created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Lubrificantes', description: 'Lubrificantes à base de água, silicone e funcionais', created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Lingeries', description: 'Kits sensuais, bodies e conjuntos exclusivos', created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Plugs & Acessórios', description: 'Plugs de silicone cirúrgico e metais nobres', created_at: new Date().toISOString() },
  { id: 'cat-5', name: 'Anéis & Estimuladores', description: 'Anéis penianos vibratórios e bullet estimuladores', created_at: new Date().toISOString() },
  { id: 'cat-6', name: 'Cosméticos & Óleos', description: 'Óleos de massagem beijáveis e velas aromáticas', created_at: new Date().toISOString() },
  { id: 'cat-7', name: 'Jogos & Kits', description: 'Kits de casal, dados eróticos e cartões de prazer', created_at: new Date().toISOString() },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'PP-EXC-01',
    barcode: '789123456001',
    name: 'Gel Excitante Xana Loka Fogo & Gelo 15g',
    brand: 'Intt Cosmetics',
    category_id: 'cat-1',
    supplier_id: 'sup-1',
    buy_price: 18.50,
    sell_price: 49.90,
    stock: 24,
    min_stock: 5,
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=75&w=500&auto=format&fit=crop',
    description: 'Gel vibratório e pulsante com efeito esquenta e esfria simultâneo. Fórmula premium dermatologicamente testada para experiências inesquecíveis.',
    active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-2',
    sku: 'PP-LUB-02',
    barcode: '789123456002',
    name: 'Lubrificante Premium Sabor Morango & Champagne 100ml',
    brand: 'Pink Pulse Signature',
    category_id: 'cat-2',
    supplier_id: 'sup-1',
    buy_price: 22.00,
    sell_price: 59.90,
    stock: 35,
    min_stock: 8,
    image_url: 'https://images.unsplash.com/photo-1608248597260-2647c29377d2?q=75&w=500&auto=format&fit=crop',
    description: 'Lubrificante corporal à base de água com textura sedosa, sabor refinado de morango com champagne e hidratação prolongada sem grudar.',
    active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-3',
    sku: 'PP-LNG-03',
    barcode: '789123456003',
    name: 'Body Rendado Velvet Orchid Noir',
    brand: 'Lingerie Luxe',
    category_id: 'cat-3',
    supplier_id: 'sup-2',
    buy_price: 65.00,
    sell_price: 189.90,
    stock: 12,
    min_stock: 3,
    image_url: 'https://images.unsplash.com/photo-1583846783214-7229a91b20ed?q=75&w=500&auto=format&fit=crop',
    description: 'Body em renda francesa de alta elasticidade com detalhes em tiras strappy e fechamento ajustável. Elegância e sedução na medida certa.',
    active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-4',
    sku: 'PP-PLG-04',
    barcode: '789123456004',
    name: 'Plug Anal em Cristal Violeta com Joia Formato Coração',
    brand: 'Pink Pulse Luxury',
    category_id: 'cat-4',
    supplier_id: 'sup-2',
    buy_price: 35.00,
    sell_price: 119.90,
    stock: 18,
    min_stock: 4,
    image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=75&w=500&auto=format&fit=crop',
    description: 'Plug anatômico em metal polido cirúrgico com pedra de cristal lapidada em formato de coração violeta. Toque frio aveludado e visual espetacular.',
    active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-5',
    sku: 'PP-ANE-05',
    barcode: '789123456005',
    name: 'Anel Vibratório Couples Pulse 10 Modos',
    brand: 'Pipedream Pulse',
    category_id: 'cat-5',
    supplier_id: 'sup-1',
    buy_price: 42.00,
    sell_price: 139.90,
    stock: 15,
    min_stock: 5,
    image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=75&w=500&auto=format&fit=crop',
    description: 'Anel duplo estimulador com motor turbo silencioso, silicone aveludado de grau médico e recarregável via USB magnético.',
    active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-6',
    sku: 'PP-COS-06',
    barcode: '789123456006',
    name: 'Vela de Massagem Aromática Baunilha & Ylang Ylang 80g',
    brand: 'Boutique Aromas',
    category_id: 'cat-6',
    supplier_id: 'sup-2',
    buy_price: 25.00,
    sell_price: 79.90,
    stock: 20,
    min_stock: 5,
    image_url: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=75&w=500&auto=format&fit=crop',
    description: 'Vela dermatológica que derrete em óleo morno nutritivo de massagem. Perfume afrodisíaco relaxante com manteiga de karité e óleo de amêndoas.',
    active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-7',
    sku: 'PP-KIT-07',
    barcode: '789123456007',
    name: 'Kit Casal Sedução Total - Caixa Secreta Pink Pulse',
    brand: 'Pink Pulse VIP',
    category_id: 'cat-7',
    supplier_id: 'sup-1',
    buy_price: 95.00,
    sell_price: 299.90,
    stock: 8,
    min_stock: 2,
    image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=75&w=500&auto=format&fit=crop',
    description: 'Kit completo contendo 1 Venda em Cetim Noir, 1 Gel Excitante, 1 Óleo Corporal Beijável e 1 Baralho de Desafios Sensoriais para casais.',
    active: true,
    created_at: new Date().toISOString()
  }
];
